name: flutter_easyloading
description: A clean and lightweight loading,toast widget for Flutter
version: 3.0.5
homepage: https://github.com/nslogx/flutter_easyloading

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
